apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.protobuf'


def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    signingConfigs {
        main {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    compileSdkVersion 28
    defaultConfig {
        applicationId "jauler.com.telemetry"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 45
        versionName "2.0.20"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.main
        }
        debug {
            applicationIdSuffix ".debug"
            signingConfig signingConfigs.main
        }
    }

	compileOptions {
		sourceCompatibility javaSourceCompatibility
		targetCompatibility javaTargetCompatibility
	}

    lintOptions {
        abortOnError false
    }

    sourceSets {
        main {
            proto {
                srcDir 'src/main/proto'
            }
        }
    }
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.21.12'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option 'lite'
                }
            }
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.preference:preference:1.0.0'
    implementation 'com.jaredrummler:colorpicker:1.1.0'
    implementation 'com.github.mik3y:usb-serial-for-android:3.4.6'
    implementation 'com.nex3z:flow-layout:1.3.0'
    implementation 'com.github.deano2390:MaterialShowcaseView:1.3.4'
    implementation 'org.osmdroid:osmdroid-android:6.1.20'
    implementation 'com.google.protobuf:protobuf-javalite:3.21.12'
    //testImplementation 'deviandroidx.test:core:1.2.0'
    testImplementation 'org.mockito:mockito-core:1.10.19'
	implementation 'com.google.android:flexbox:2.0.1'
}

